---
- name: "Install ldap-utils"
  ansible.builtin.package:
    update_cache: true
    name:
      - "ldap-utils"

- name: "Install ApacheDS"
  block:
    - name: "Check if install dir exist"
      register: file_check
      ansible.builtin.stat:
        path: "{{ install_apacheds__path }}"

    - name: "Create install dir"
      when: not file_check.stat.exists
      ansible.builtin.file:
        path: "{{ install_apacheds__path }}"
        state: directory
        recurse: yes
        mode: "0700"
        group: "{{ install_apacheds__group }}"
        owner: "{{ install_apacheds__user }}"

    - name: "Download defined version and install ApacheDS"
      ansible.builtin.unarchive:
        src: "https://dlcdn.apache.org//directory/apacheds/dist/{{ install_apacheds__version }}/apacheds-{{ install_apacheds__version }}.tar.gz"
        dest: "{{ install_apacheds__path }}"
        remote_src: yes
        mode: "0700"
        group: "{{ install_apacheds__group }}"
        owner: "{{ install_apacheds__user }}"
        extra_opts: [--strip-components=1]

- name: "Create instances"
  loop: "{{ install_apacheds__instances }}"
  loop_control:
    loop_var: instance
    index_var: index
  ansible.builtin.include_tasks:
    file: "create_instance.yml"
