---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_apacheds"
      tags:
        - "labocbz.install_apacheds"
      vars:
        install_apacheds__version: "{{ inv_install_apacheds__version }}"
        install_apacheds__user: "{{ inv_install_apacheds__user }}"
        install_apacheds__group: "{{ inv_install_apacheds__group }}"
        install_apacheds__install_dir: "{{ inv_install_apacheds__install_dir }}"
        install_apacheds__path: "{{ inv_install_apacheds__path }}"
        install_apacheds__instances: "{{ inv_install_apacheds__instances }}"
      ansible.builtin.include_role:
        name: "labocbz.install_apacheds"
